app:
    resource: "@AppBundle/Controller"
    type: annotation
app.profile:
    resource: "@AppBundle/Controller/ProfileController.php"
    type: annotation
    prefix: /profile
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"