# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_user_provider.class: AppBundle\OAuth\OAuthUserProvider
#    parameter_name: value

services:
    app.user:
        class: AppBundle\Service\UserService
        arguments: ["@doctrine.orm.entity_manager"]
    app.tests:
        class: AppBundle\Service\TestService
        arguments: ["@doctrine.orm.entity_manager"]
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager",{facebook: facebook_id, google: google_id}]
    app.email_send:
        class: AppBundle\Event\EmailSender
        arguments: ["@event_dispatcher"]
    app.event_subscriber:
        class: AppBundle\Event\EventSubscriber
        arguments: [ "@service_container" ]
        tags:
          - {name: kernel.event_subscriber, event: app.email_send }