services:
#    nfq_sandbox.example:
#        class: NFQ\SandboxBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  app.boeing:
    class: NFQ\SandboxBundle\Service\Boeing
    factory: ["@app.boeing_factory", create]

  app.boeing_factory:
    class: NFQ\SandboxBundle\Service\BoeingFactory
    arguments: ["@event_dispatcher"]

  app.event_listener:
            class: NFQ\SandboxBundle\Event\EventListener
            tags:
                - { name: kernel.event_listener, event: app.pre_create, method: makeChanges }
  app.sub:
    class: NFQ\SandboxBundle\Event\Sub
    tags:
      - { name: kernel.event_subscriber}