services:
#    nfq_sandbox.example:
#        class: NFQ\SandboxBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  app.helicopter_set_get:
    class: NFQ\SandboxBundle\Service\Helicopter
    factory: ["@app.helicopter_factory",createAndSetEngine]
  app.helicopter:
    class: NFQ\SandboxBundle\Service\Helicopter
    factory: ["@app.helicopter_factory",create]
  app.helicopter_factory:
    class: NFQ\SandboxBundle\Service\HelicopterFactory
    arguments: ["@event_dispatcher"]
  app.event_listener:
    class: NFQ\SandboxBundle\Event\EventListener
    tags:
        - {name: kernel.event_listener, event: app.create_event, method: makeChanges }
  app.helicopter_sub:
      class: NFQ\SandboxBundle\Service\Helicopter
      factory: ["@app.helicopter_factory",createSub]
  app.event_subscriber:
    class: NFQ\SandboxBundle\Event\EventSubscriber
    tags:
            - {name: kernel.event_subscriber, event: app.create_event, method: changeEngine }